### PR TITLE
Add interface for linux and add extended device information in info command

### PR DESCRIPTION
**Pull request by fernsehkind**

### CODE REVIEW

**Comment by fernsehkind** [comment]
@rsc-dev : Very very nice work from you so far. Where or how did you get the interface for the polar loop files?

**Comment by rsc-dev** [comment]
@fernsehkind: I will try to explain everything here: http://rm2084.blogspot.com/. Send me an email if you want more info - roscoe@o2.pl.

**Comment by fernsehkind** [comment]
@rsc-dev: I'm dying to hear how you disassembled the protocol. For me it's OK, when you explain it in your blog. Otherwise you have to explain it twice. Do you have any plans how to proceed with loophole? I'm trying to port it to raspi and use a database and a web frontend to access the data...

**Comment by rsc-dev** [comment]
@fernsehkind: Great. Spoiler - Polar loop is using Google Protocol Buffer for both communication and storing data (BPB files). I created a python module (pbd - https://github.com/rsc-dev/pbd) to reverse protobuf descriptors. I managed to restore proto files and recompiled for Python (pbd/ direcotry). Those binary protobuf descriptors Polar included in Android app. 

I want the Loophole to become a full API to access Polar devices (I believe this interface is common for other Polar devices). I thought about web-app, but unfortunatelly I do not have enought time.

If you need any help - let me know.

**Comment by fernsehkind** [comment]
@rsc-dev and @k3ho:
I just want to let you know that I just published my first version of PALOR - a web interface for activity trackers. It uses loophole to dump the devices and visualize the activity data.

At the moment I only evaluate the calories and steps per day.

https://github.com/fernsehkind/PALOR

**Comment by rsc-dev** [comment]
@fernsehkind, @k3ho - Great project! My next version will include DELETE and PUT commands + probably I will publish 'plain' protobuf descriptors.

**Comment by fernsehkind** [comment]
@rsc-dev : Did you already test it? Does it work on your system?

**Comment by rsc-dev** [comment]
@fernsehkind: Maybe you should join https://gitter.im/pcolby/bipolar?

**Comment by rsc-dev** [comment]
@fernsehkind: Will do it today and let you know.

**Pull request merged**
