### PR TITLE
Fix#8 USB permission problem

### PR DESCRIPTION
**Pull request by jedie**
see #8

### CODE REVIEW

**Review by rsc-dev — APPROVED** [review]
Merging USB insufficient permissions exception handling.

**Comment by rsc-dev** [comment]
USB insufficient permissions exception handling.

**Comment by jedie** [comment]
This is closed, but not merged, isn't it?

Why?

**Comment by rsc-dev** [comment]
You sure? I will double check later. It should be merged.

04.04.2017 16:47 "Jens Diemer" <notifications@github.com> napisał(a):

**Comment by jedie** [comment]
unbenannt

**Comment by rsc-dev** [comment]
Merged :)

**Pull request merged**
